### ISSUE TITLE
invalid conversion for "void *" to "const void *"

### ISSUE THREAD

**Issue by yaochx** [purine/purine2#10]
make mpi.cpp with Error like this:
/home/yaocx/workspace/purine2/operations/src/mpi.cpp:14:44: error: invalid conversion from ‘const void_’ to ‘void_’ [-fpermissive]

I just add (void_)  in line (14) of mpi.cpp file to make
  MPI_CHECK(MPI_Isend((void_)inputs_[0]->cpu_data(), inputs_[0]->size().count(),
          MPI_FLOAT, dest, tag, MPI_COMM_WORLD, &request));

or maybe you can change the makefile with flag -fpermissive

Any good advice?

**Comment by boringwar** [comment]
You should use newer version of MPI perhaps, the definition of  MPI_Isend has changed.

**Comment by mavenlin** [comment]
@hkcqr Correct, @yaochx  the version number I use here is mpich 3.0.4
