### ISSUE TITLE
example nin_cifar does not work

### ISSUE THREAD

**Issue by zhxfl** [purine/purine2#16]
2.411124 0.132812
2.542028 0.132812
2.302772 0.125000
2.312779 0.109375
2.310245 0.117188
2.302449 0.101562
2.306294 0.085938
2.301918 0.148438
2.302899 0.031250
2.302605 0.132812
2.302575 0.132812
2.302580 0.109375
2.302587 0.093750
2.302583 0.117188
2.302583 0.054688
2.302583 0.093750
2.302583 0.070312
2.302583 0.109375
2.302583 0.078125
2.302583 0.125000
2.302583 0.109375
2.302583 0.062500
2.302583 0.109375
2.302583 0.093750
2.302583 0.125000
2.302583 0.109375
2.302583 0.070312
2.302583 0.093750

I print the loss and accuracy and find loss becomes const after several iterator and net does not convergence. I think it is a bug.

By the way, example goolent is work.

**Comment by shiyemin** [comment]
You should edit nin_cifar.cpp to get it  work.

**Comment by zhxfl** [comment]
I get it
