### ISSUE TITLE
There is no definition of "cudnnGetErrorString"

### ISSUE THREAD

**Issue by peterson123** [purine/purine2#7]
Hi, 

when I try to compile the purine code with "make" command, it show there is no definition of "cudnnGetErrorString", please check

**Comment by RiemannLiu** [comment]
Are you using cudnn R1 version? In this version, the function has not been defined, you need to implement it in cuda.hpp/cuda.cpp. In purine2, cudnn R2 has been used.

**Comment by peterson123** [comment]
hi, this problem is solved by using cudnn v2 rc3, the cudnn R1 version has no definition of "cudnnGetErrorString"
