### ISSUE TITLE
Randomly stop training in nin_cifar10

### ISSUE THREAD

**Issue by cwfxcz** [purine/purine2#8]
Hi,
After struggling through all the compile problems and a quick lesson about MPI, I can finally use the nin_cifar10 example, but I find that the training process may be hung and the GPU utilization falls to 0% at any time during training(sometimes after hundreds of iterations sometimes even more). Can that be the problem about async()/ sync()?
Thanks

**Comment by mavenlin** [comment]
Hi cwfxcz, are you running the example with GPUs on different machines, or is it single machine multiple GPUs?

**Comment by cwfxcz** [comment]
I run it on a single machine, single GPU because I find the {rank, device} pair is {0, 0}.

**Comment by mavenlin** [comment]
It is strange, I could not reproduce the behavior on my machine.

**Comment by cwfxcz** [comment]
Thanks for your reply,
   Maybe there's something wrong about my configuration. Do you use 'mpic++' as the compiler and execute the example using 'mpirun'?

**Comment by mavenlin** [comment]
Nope, I compiled with gcc-4.8. Running is fine either with mpirun or direct run (single process).
BTW, the mpi I use is mpich2 because it supports multithreading, the openmpi originally installed on ubuntu14.04 is removed and mpich2 is install through apt-get.

**Comment by cwfxcz** [comment]
Hi, Lin
I replace OpenMPI with mpich2 as you said, and it works! 
Thanks
